### ISSUE TITLE
"Failed to connect to event stream" frequently for xarray's binder

### ISSUE THREAD

**Issue by max-sixty** [jupyterhub/binder#180] opened 2020-01-09 14:39 UTC
Firstly, thanks for the awesome product!

I'm frequently seeing "Failed to connect to event stream" on the xarray examples (e.g. https://mybinder.org/v2/gh/pydata/xarray/master?urlpath=lab/tree/doc/examples/multidimensional-coords.ipynb). I tried using both Lab and normal notebooks. Is there somewhere we can see more logs to assess what the problem is?

I tried the Dask one and it works well: https://mybinder.org/v2/gh/dask/dask-examples/master?urlpath=lab. It doesn't specify the file; I tried changing xarray's to the path but no luck. Potentially the different is in the requirements?

Ref #155, which had a similar error message. It was closed awaiting more reports.

**Comment by betatim** [comment] 2020-01-09 17:23
The error is annoying but harmless, you can reload the page to "reconnect". Thanks for reporting it though because otherwise we don't notice how often this happens!

We still don't have a good idea when exactly it happens, other than "sometimes and shaky internet connections or large amounts of output make it worse". For example for me the xarray binder built just fine on the first try now :-/

This means it is a bit tricky to know what the actionable thing is to do here. Maybe something to think about is to automate the reloading of the page when this error happens as that is what we tell users to do manually. What do you think/

**Comment by max-sixty** [comment] 2020-01-09 19:06
Thanks for the fast reply.

But I don't think reloading makes it work: I did try that previously, at least half a dozen times over ~15 minutes. My colleague tried too. I also just tried again (i.e. 4 hours after the original issue) and I see the same error...

**Comment by choldgraf** [comment] 2020-01-10 00:31
@max-sixty could you try launching it on a different BinderHub instance? e.g. hard-code `gke.` or `gesis.` before the "mybinder.org" bit...maybe it's a hub-specific thing?

**Comment by max-sixty** [comment] 2020-01-10 00:51
It now works (on https://hub-binder.mybinder.ovh/user/pydata-xarray-am8ztkkl/lab, though I guess that's temporary)

Are there any logs to work out what's happening / diagnose the problem? I'm happy to help...

**Comment by choldgraf** [comment] 2020-01-10 00:53
unfortunately not - the annoying thing about this particular bug is that it is the logs communication breaking down, so it is hard to pinpoint what's going wrong :-(

**Comment by max-sixty** [comment] 2020-01-13 15:53
I just checked again, and it's broken again :(

https://mybinder.org/v2/gh/pydata/xarray/master?urlpath=lab/tree/doc/examples/multidimensional-coords.ipynb

> @max-sixty could you try launching it on a different BinderHub instance? e.g. hard-code `gke.` or `gesis.` before the "mybinder.org" bit...maybe it's a hub-specific thing?

I tried adding `gke` and `gesis` to the front (i.e. https://gke.mybinder.org/v2/gh/pydata/xarray/master?urlpath=lab/tree/doc/examples/multidimensional-coords.ipynb, https://notebooks.gesis.org/binder/v2/gh/pydata/xarray/master?urlpath=lab/tree/doc/examples/multidimensional-coords.ipynb), and both failed

Could it be that xarray's `environment.yml` isn't fully pinned? I'm trying to see the difference between Dask's successful launches and xarray's failures

**Comment by betatim** [comment] 2020-01-14 06:22
The place I'd search is a difference in the amount of output produced in each build and the network connection you are on. The build continues happily in the background even when you are disconnected. The error is purely about the network connection between your browser and mybinder.org

**Comment by max-sixty** [comment] 2020-01-14 15:12
> The place I'd search is a difference in the amount of output produced in each build and the network connection you are on.

Where can we see the output?

**Comment by betatim** [comment] 2020-01-20 08:57
You see the log output in the same place as the error message you reported. I don't know if a difference in the amount of text produced there is a reason for the error to happen but I could imagine that it isn't impossible :)

**Comment by max-sixty** [comment] 2020-01-20 17:23
Thanks for engaging @betatim . Unfortunately I only see that line, and can't seem to scroll to any other output. (FWIW it seems to break more often than work, so if you click on the links above you can probably see the same thing). Am I missing something?

![image](https://user-images.githubusercontent.com/5635139/72746273-adbdbd80-3b7f-11ea-884b-7b0952849eaa.png)

**Comment by betatim** [comment] 2020-01-21 06:52
That is the weird thing, for me it works (unscientifically) 99% of the time, at least I hardly ever see the error. I tried refreshing your links many times to see if that would provoke it or some other repos that have caused this problem in the past. My hunch is that this has something to do with the network between the user and mybinder.org, but don't know what it is. This is based on the fact that there are people for whom this isn't a problem at all and people for who it is reproducibly&frequently a problem.

Some wild guesses: Different browsers? Different corporate network settings/firewalls? Mobile vs wired internet? Ad blockers?

**Comment by max-sixty** [comment] 2020-01-24 14:28
Another oddity is that it's only xarray that seems to fail. As above, the dask examples work fine, and I just tried Beaker [here](https://mybinder.org/v2/gh/twosigma/beakerx/1.2.0?filepath=StartHere.ipynb). 

It's a shame because Binder is such a great resource for a library like xarray, but people's first impressions may be that it's poorly maintained. 

Any ideas why xarray might fail while others succeed?

**Comment by betatim** [comment] 2020-01-25 07:00
I'll close this issue as it is a duplicate of https://github.com/jupyterhub/binder/issues/180 which tracks the same problem. I don't believe this is a problem with the source repository so we only need one issue to track the problem and work on a solution.

**Closed by betatim** 2020-01-25 07:00 UTC
